import "./globals.css";
import type { Metadata } from "next";

import { AppProvider } from "@/context/appcontext";

export const metadata: Metadata = {
  title: "Net Property",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AppProvider> 
        <body className="bg-gray-200 2xl:w-[70vw] 2xl:mx-[15vw]">{children}</body>
      </AppProvider>
    </html>
  );
}
