"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Provider } from "react-redux";
import { store } from "@/utils/store";
import { getUser } from "@/slice/authenticationSlice";
import { getClientToken } from "@/service/token";

export const metadata: Metadata = {
  title: "Net Property",
  description: "Generated by create next app",
};

getClientToken().then((token) => store.dispatch(getUser(token)));

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Provider store={store}>
        <body className="bg-gray-200 2xl:w-[70vw] 2xl:mx-[15vw]">
          {children}
        </body>
      </Provider>
    </html>
  );
}
